#!/bin/bash

# Email Configuration Diagnostics for Production
# This script helps diagnose email sending issues on Railway/production

echo "📧 Email Configuration Diagnostics"
echo "===================================="
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}Common causes of 500 errors when sending emails:${NC}"
echo "1. SMTP credentials not set in Railway environment"
echo "2. Gmail blocking 'less secure apps' or app passwords not used"
echo "3. SMTP port blocked by hosting provider"
echo "4. Timeout issues (taking too long to connect)"
echo "5. Environment variables not loaded properly"
echo ""

echo "===================================="
echo "Required Environment Variables:"
echo "===================================="
echo ""
echo "SMTP_HOST=smtp.gmail.com (or your SMTP server)"
echo "SMTP_PORT=587 (or 465 for SSL)"
echo "SMTP_USER=your-email@gmail.com"
echo "SMTP_PASS=your-app-password (NOT your Gmail password!)"
echo "SMTP_FROM_EMAIL=noreply@yourdomain.com"
echo ""

echo "===================================="
echo "Gmail Setup Instructions:"
echo "===================================="
echo ""
echo "If using Gmail, you MUST use App Password:"
echo ""
echo "1. Go to: https://myaccount.google.com/security"
echo "2. Enable 2-Step Verification (required)"
echo "3. Go to: https://myaccount.google.com/apppasswords"
echo "4. Generate an 'App Password' for 'Mail'"
echo "5. Copy the 16-character password (no spaces)"
echo "6. Use this as SMTP_PASS, NOT your regular Gmail password"
echo ""

echo "===================================="
echo "Railway Environment Setup:"
echo "===================================="
echo ""
echo "Add these variables in Railway:"
echo "  Project → Settings → Variables → Add"
echo ""
echo "SMTP_HOST: smtp.gmail.com"
echo "SMTP_PORT: 587"
echo "SMTP_USER: your-email@gmail.com"
echo "SMTP_PASS: xxxx xxxx xxxx xxxx (16-char app password)"
echo "SMTP_FROM_EMAIL: noreply@toolbay.store"
echo ""
echo -e "${YELLOW}Important: Redeploy after adding variables!${NC}"
echo ""

echo "===================================="
echo "Alternative: Use SendGrid or Resend"
echo "===================================="
echo ""
echo "For production, consider using dedicated email services:"
echo ""
echo "Option 1: SendGrid (Free tier: 100 emails/day)"
echo "  - Sign up: https://sendgrid.com"
echo "  - Get API key"
echo "  - Use SMTP relay:"
echo "    SMTP_HOST=smtp.sendgrid.net"
echo "    SMTP_PORT=587"
echo "    SMTP_USER=apikey"
echo "    SMTP_PASS=your-sendgrid-api-key"
echo ""
echo "Option 2: Resend (Free tier: 100 emails/day)"
echo "  - Sign up: https://resend.com"
echo "  - More reliable than Gmail"
echo "  - Better deliverability"
echo ""

echo "===================================="
echo "Testing Email Configuration:"
echo "===================================="
echo ""
echo "1. Check Railway logs for errors:"
echo "   railway logs --follow"
echo ""
echo "2. Look for errors like:"
echo "   - 'Invalid login' → Wrong SMTP credentials"
echo "   - 'Connection timeout' → Port blocked or wrong host"
echo "   - 'Authentication failed' → Need app password"
echo "   - 'ECONNREFUSED' → Can't reach SMTP server"
echo ""

echo "===================================="
echo "Quick Fix Checklist:"
echo "===================================="
echo ""
echo "□ Using Gmail App Password (not regular password)"
echo "□ 2-Step Verification enabled in Gmail"
echo "□ All SMTP_* variables set in Railway"
echo "□ SMTP_PORT is 587 (not 465 unless using secure:true)"
echo "□ Redeployed Railway after adding variables"
echo "□ Checked Railway logs for specific error"
echo "□ Tested with curl from production server"
echo ""

echo "===================================="
echo "Debug Command for Railway:"
echo "===================================="
echo ""
echo "Run this in Railway shell to check environment:"
echo ""
echo "echo SMTP_HOST: \$SMTP_HOST"
echo "echo SMTP_PORT: \$SMTP_PORT"
echo "echo SMTP_USER: \$SMTP_USER"
echo "echo SMTP_PASS: \${SMTP_PASS:0:4}**** (first 4 chars)"
echo ""

echo "===================================="
echo -e "${GREEN}Most Common Fix:${NC}"
echo "===================================="
echo ""
echo -e "${YELLOW}1. Generate Gmail App Password${NC}"
echo "   https://myaccount.google.com/apppasswords"
echo ""
echo -e "${YELLOW}2. Add to Railway:${NC}"
echo "   SMTP_PASS = xxxx xxxx xxxx xxxx"
echo ""
echo -e "${YELLOW}3. Redeploy${NC}"
echo "   railway up"
echo ""

echo "===================================="
echo "Need more help? Check Railway logs:"
echo "===================================="
echo "railway logs --tail 100 | grep -i 'email\\|smtp\\|mail'"
echo ""
