/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    tags: Tag;
    tenants: Tenant;
    transactions: Transaction;
    orders: Order;
    reviews: Review;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    categories: {
      subcategories: 'categories';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  username: string;
  roles?: ('super-admin' | 'tenant' | 'client')[] | null;
  tenants?:
    | {
        tenant: string | Tenant;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * 🏪 Tenant Management - Super Admin Guide: (1) Review RDB Certificate, (2) Set Verification Status, (3) Check Is Verified, (4) Add Notes, (5) Enable Merchant Capabilities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: string;
  /**
   * This is the name of the store (e.g. Antonio's Store)
   */
  name: string;
  /**
   * This is the subdomain for the store (e.g. [slug].toolboxx.com)
   */
  slug: string;
  image?: (string | null) | Media;
  /**
   * Tax Identification Number (TIN) - Required for Rwandan businesses
   */
  tinNumber: string;
  /**
   * Store Manager ID or Passport Number
   */
  storeManagerId: string;
  /**
   * Rwanda Development Board (RDB) Registration Certificate (required for verification)
   */
  rdbCertificate?: (string | null) | Media;
  /**
   * Choose your preferred payment method
   */
  paymentMethod: 'bank_transfer' | 'momo_pay';
  /**
   * Bank name for transfers
   */
  bankName?: string | null;
  /**
   * Bank account number for transfers
   */
  bankAccountNumber?: string | null;
  /**
   * Mobile Money (MOMO) Pay Code
   */
  momoPayCode?: string | null;
  /**
   * ⚠️ REQUIRED: Mobile Money Code (integer) for receiving payments - Used in dial code *182*8*1*CODE*Amount#
   */
  momoCode?: number | null;
  /**
   * Business name for MoMo account (shown to customers)
   */
  momoAccountName?: string | null;
  /**
   * Total revenue after platform fees (RWF) - Updated automatically after payment verification
   */
  totalRevenue?: number | null;
  /**
   * ✅ SUPER ADMIN: Check this to enable tenant capabilities (product creation, selling). Only check after verifying documents.
   */
  isVerified?: boolean | null;
  /**
   * 🔍 SUPER ADMIN: Set verification stage. 'Document Verified' allows selling. 'Physically Verified' allows merchant management.
   */
  verificationStatus?: ('pending' | 'document_verified' | 'physically_verified' | 'rejected') | null;
  /**
   * 📝 SUPER ADMIN: Add notes about verification decision, document quality, or follow-up actions needed.
   */
  verificationNotes?: string | null;
  /**
   * 📋 Tenant has requested verification review
   */
  verificationRequested?: boolean | null;
  /**
   * 📅 When verification was requested
   */
  verificationRequestedAt?: string | null;
  /**
   * Tenant has requested physical verification
   */
  physicalVerificationRequested?: boolean | null;
  /**
   * Date when physical verification was requested
   */
  physicalVerificationRequestedAt?: string | null;
  /**
   * 3-8 images from physical verification visit
   */
  physicalVerificationImages?:
    | {
        image: string | Media;
        /**
         * Brief description of what this image shows
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Signed consent document (PDF) from physical verification
   */
  signedConsent?: (string | null) | Media;
  /**
   * 🏪 SUPER ADMIN: Enable merchant account management. Usually enabled after document or physical verification.
   */
  canAddMerchants?: boolean | null;
  /**
   * Date when tenant was verified
   */
  verifiedAt?: string | null;
  /**
   * Super admin who verified this tenant
   */
  verifiedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alternative text for accessibility (auto-generated if not provided)
   */
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  color?: string | null;
  parent?: (string | null) | Category;
  subcategories?: {
    docs?: (string | Category)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * You must verify your account before creating products
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Main product image - this will be the first thing customers see
   */
  image: string | Media;
  /**
   * Additional product image (optional)
   */
  cover?: (string | null) | Media;
  /**
   * Product gallery - up to 24 photos and videos
   */
  gallery?:
    | {
        media: string | Media;
        id?: string | null;
      }[]
    | null;
  name: string;
  /**
   * Describe your product's key features and condition
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Price in Rwandan Francs (RWF)
   */
  price: number;
  /**
   * Available quantity in stock
   */
  quantity: number;
  /**
   * Unit of measurement for this product
   */
  unit:
    | 'unit'
    | 'piece'
    | 'box'
    | 'pack'
    | 'bag'
    | 'kg'
    | 'gram'
    | 'meter'
    | 'cm'
    | 'liter'
    | 'sqm'
    | 'cbm'
    | 'set'
    | 'pair'
    | 'roll'
    | 'sheet'
    | 'carton'
    | 'pallet';
  /**
   * Minimum quantity that can be ordered at once
   */
  minOrderQuantity?: number | null;
  /**
   * Maximum quantity per order (leave empty for no limit)
   */
  maxOrderQuantity?: number | null;
  /**
   * Current stock availability status
   */
  stockStatus: 'in_stock' | 'low_stock' | 'out_of_stock' | 'pre_order';
  /**
   * Alert when stock falls below this number
   */
  lowStockThreshold?: number | null;
  /**
   * Allow customers to order even when out of stock
   */
  allowBackorder?: boolean | null;
  /**
   * Select the most appropriate category for your product
   */
  category: string | Category;
  /**
   * Add tags to help customers find your product
   */
  tags?: (string | Tag)[] | null;
  /**
   * Tenant who owns this product
   */
  tenant?: (string | null) | Tenant;
  refundPolicy?: ('30-day' | '14-day' | '7-day' | '3-day' | '1-day' | 'no-refunds') | null;
  /**
   * Protected content only visible to customers after purchase. Add product documentation, downloadable files, getting started guides, and bonus materials. Supports Markdown formatting
   */
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If checked, this product will not be shown on the public storefront
   */
  isPrivate?: boolean | null;
  /**
   * If checked, this product will be archived
   */
  isArchived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  products?: (string | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Payment transactions pending verification - Transactions are created automatically through checkout
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  /**
   * Auto-generated payment reference (e.g., PAY1AB2C3D4E)
   */
  paymentReference: string;
  /**
   * Current status of the transaction
   */
  status: 'pending' | 'awaiting_verification' | 'verified' | 'rejected' | 'expired';
  /**
   * Customer who made the purchase
   */
  customer: string | User;
  /**
   * Customer name for quick reference
   */
  customerName: string;
  /**
   * Customer email for notifications
   */
  customerEmail: string;
  /**
   * Phone number used for MoMo payment
   */
  customerPhone?: string | null;
  /**
   * Customer shipping address
   */
  shippingAddress?: {
    /**
     * Address line 1
     */
    line1?: string | null;
    /**
     * City
     */
    city?: string | null;
    /**
     * Country
     */
    country?: string | null;
  };
  /**
   * Store receiving the payment
   */
  tenant: string | Tenant;
  /**
   * Products in this transaction
   */
  products: {
    product: string | Product;
    price: number;
    id?: string | null;
  }[];
  /**
   * Total amount in RWF
   */
  totalAmount: number;
  /**
   * Platform fee (10% of total)
   */
  platformFee: number;
  /**
   * Amount for tenant after platform fee
   */
  tenantAmount: number;
  /**
   * MTN Mobile Money Transaction ID (from customer SMS)
   */
  mtnTransactionId?: string | null;
  /**
   * Transaction expires after 48 hours
   */
  expiresAt: string;
  /**
   * When the payment was verified
   */
  verifiedAt?: string | null;
  /**
   * Admin/Tenant who verified the payment
   */
  verifiedBy?: (string | null) | User;
  /**
   * Reason for rejection
   */
  rejectionReason?: string | null;
  /**
   * Internal notes about this transaction
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Unique order reference number
   */
  orderNumber: string;
  name: string;
  /**
   * Customer who placed the order
   */
  user: string | User;
  products: {
    product: string | Product;
    quantity: number;
    /**
     * Price of the product at time of purchase
     */
    priceAtPurchase: number;
    id?: string | null;
  }[];
  /**
   * Main product (for backwards compatibility)
   */
  product: string | Product;
  /**
   * Total order amount in RWF
   */
  totalAmount: number;
  /**
   * Related verified transaction
   */
  transaction?: (string | null) | Transaction;
  /**
   * Order fulfillment status. Orders start as 'pending' after payment verification, then move through shipped → delivered → completed when customer confirms receipt.
   */
  status: 'pending' | 'shipped' | 'delivered' | 'completed' | 'cancelled';
  /**
   * Date when customer confirmed receipt of item
   */
  confirmedAt?: string | null;
  /**
   * Date when item was shipped
   */
  shippedAt?: string | null;
  /**
   * Date when item was delivered
   */
  deliveredAt?: string | null;
  /**
   * Customer confirmed receipt of order
   */
  received?: boolean | null;
  /**
   * Transaction ID from mobile money or bank transfer
   */
  transactionId: string;
  /**
   * Payment method used for this transaction
   */
  paymentMethod: 'mobile_money' | 'bank_transfer';
  /**
   * Bank name or mobile money provider (MTN, Airtel, etc.)
   */
  bankName?: string | null;
  /**
   * Bank account number or mobile money number
   */
  accountNumber?: string | null;
  /**
   * Transaction amount in Rwandan Francs (RWF)
   */
  amount: number;
  /**
   * Currency (Rwandan Francs)
   */
  currency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  description: string;
  rating: number;
  product: string | Product;
  user: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'tenants';
        value: string | Tenant;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  username?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  color?: T;
  parent?: T;
  subcategories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  image?: T;
  cover?: T;
  gallery?:
    | T
    | {
        media?: T;
        id?: T;
      };
  name?: T;
  description?: T;
  price?: T;
  quantity?: T;
  unit?: T;
  minOrderQuantity?: T;
  maxOrderQuantity?: T;
  stockStatus?: T;
  lowStockThreshold?: T;
  allowBackorder?: T;
  category?: T;
  tags?: T;
  tenant?: T;
  refundPolicy?: T;
  content?: T;
  isPrivate?: T;
  isArchived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  tinNumber?: T;
  storeManagerId?: T;
  rdbCertificate?: T;
  paymentMethod?: T;
  bankName?: T;
  bankAccountNumber?: T;
  momoPayCode?: T;
  momoCode?: T;
  momoAccountName?: T;
  totalRevenue?: T;
  isVerified?: T;
  verificationStatus?: T;
  verificationNotes?: T;
  verificationRequested?: T;
  verificationRequestedAt?: T;
  physicalVerificationRequested?: T;
  physicalVerificationRequestedAt?: T;
  physicalVerificationImages?:
    | T
    | {
        image?: T;
        description?: T;
        id?: T;
      };
  signedConsent?: T;
  canAddMerchants?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  paymentReference?: T;
  status?: T;
  customer?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  shippingAddress?:
    | T
    | {
        line1?: T;
        city?: T;
        country?: T;
      };
  tenant?: T;
  products?:
    | T
    | {
        product?: T;
        price?: T;
        id?: T;
      };
  totalAmount?: T;
  platformFee?: T;
  tenantAmount?: T;
  mtnTransactionId?: T;
  expiresAt?: T;
  verifiedAt?: T;
  verifiedBy?: T;
  rejectionReason?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  name?: T;
  user?: T;
  products?:
    | T
    | {
        product?: T;
        quantity?: T;
        priceAtPurchase?: T;
        id?: T;
      };
  product?: T;
  totalAmount?: T;
  transaction?: T;
  status?: T;
  confirmedAt?: T;
  shippedAt?: T;
  deliveredAt?: T;
  received?: T;
  transactionId?: T;
  paymentMethod?: T;
  bankName?: T;
  accountNumber?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  description?: T;
  rating?: T;
  product?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}